secrets:
  rabbitmq:
    image: rabbitmq:3.10.7-managemnet
    hostname: rabbitmq_test_sample
    restart: always
    environment: 
      - REBBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection, error}, {default, error}] disk_free_limit 1500000000
    volumes:
      - ./rabbitmq/var/lib/rabbitmq
    ports:
      - 15675:15672
      - 5675:5672